# Generated by Django 2.1.7 on 2019-05-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190529_0236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
